name: Beautiful Jekyll CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - name: Update Rubygems
      run: gem update --system

    - name: Build site with Jekyll
      run: |
        export JEKYLL_VERSION=3.8
        docker run \
          -v $(pwd):/srv/jekyll \
          -v $(pwd)/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
